// Mirrors backend ActivityActions (features/activity/ActivityActions.java) - kept in
// sync manually since the values are free-form constants, not an API-discoverable enum.
export const ActivityActions = {
  CHILD_CREATED: 'CHILD_CREATED',
  CHILD_UPDATED: 'CHILD_UPDATED',
  CHILD_DELETED: 'CHILD_DELETED',
  ATTENDANCE_RECORDED: 'ATTENDANCE_RECORDED',
  HEALTH_RECORD_CREATED: 'HEALTH_RECORD_CREATED',
  HEALTH_RECORD_DELETED: 'HEALTH_RECORD_DELETED',
  USER_CREATED: 'USER_CREATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_DELETED: 'USER_DELETED',
  GUARDIAN_CREATED: 'GUARDIAN_CREATED',
  GUARDIAN_DELETED: 'GUARDIAN_DELETED',
}
